
ERROR_TIME: 2021-07-28 21:02:31,130
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 439
ERROR_SCOPE xml_analysis error due to: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 436, in xml_analysis
    return tag_save(sentence_count, collective_results)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 314, in tag_save
    save_sentences(collective_results, path)
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 558, in save_sentences
    with open(file, mode="a+", encoding="utf-8", newline="") as results:
FileNotFoundError: [Errno 2] No such file or directory: ''

ERROR_TIME: 2021-07-28 21:02:42,332
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 885
ERROR_SCOPE Main Menu: division by zero
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 881, in run_program
    sentence_identification(collective_results_tagged, database, system_evaluation)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 572, in sentence_identification
    write_to_database(sentence.feature_assignment(), sub_sentences, system_file)
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 206, in feature_assignment
    feat_1_score = self.calculate_scores()[0]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 141, in calculate_scores
    avg_word_length = round(words/characters*100)
ZeroDivisionError: division by zero
