
ERROR_TIME: 2021-08-04 16:44:12,603
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1000
ERROR_SCOPE  'if __name__ == __main__': is due to '0)'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 983, in <module>
    run_program(default_doc, default_train,system_evaluation)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 948, in run_program
    document_classificaiton(probs)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 819, in document_classificaiton
    for word in sentence[0].split():
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 0

ERROR_TIME: 2021-08-04 17:02:01,417
FILE_NAME: app_auxiliary_functions.py
MODULE: app_auxiliary_functions
                        
LINE_NO: 984
ERROR_SCOPE Sub menu error: [Errno 2] No such file or directory: 'C:\\Users\\chris\\Desktop\\Bachleorarbeit\\app_resources\\app_dev\\test_sys.csv'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 981, in sub_menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 667, in evaluate_naive_bayes
    system = open(system_file, mode="r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\chris\\Desktop\\Bachleorarbeit\\app_resources\\app_dev\\test_sys.csv'
