
ERROR_TIME: 2021-07-28 09:21:16,020
FILE_NAME: app_auxiliary_functions.py
MODULE: app_auxiliary_functions
                        
LINE_NO: 523
ERROR_SCOPE Sub menu error: I/O operation on closed file.
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 520, in sub_menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 285, in evaluate_naive_bayes
    for row in csv_gold_reader:
ValueError: I/O operation on closed file.

ERROR_TIME: 2021-07-28 09:28:10,880
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 440
ERROR_SCOPE xml_analysis error due to: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 437, in xml_analysis
    return tag_save(sentence_count, collective_results)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 315, in tag_save
    save_sentences(collective_results, path)
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 466, in save_sentences
    number,sentence = enumerate(collective_results[res])
ValueError: too many values to unpack (expected 2)

ERROR_TIME: 2021-07-28 09:46:08,967
FILE_NAME: app_auxiliary_functions.py
MODULE: app_auxiliary_functions
                        
LINE_NO: 564
ERROR_SCOPE Sub menu error: 'int' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 561, in sub_menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\app_auxiliary_functions.py", line 281, in evaluate_sentence_tokenizer
    gold_results=gold_results.get(row[1],0)+1
AttributeError: 'int' object has no attribute 'get'
