ERROR_TIME: 2021-08-06 17:41:36,540
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1040
ERROR_SCOPE Main Menu: string index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 1035, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 640, in sentence_identification
    save_results(feat, sentence_info, sentence_file, database_file)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 557, in save_results
    if database_file: write_to_database(feat, sentence, database_file)
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 1061, in write_to_database
    sen_word_pos = element[1]
IndexError: string index out of range

ERROR_TIME: 2021-08-06 18:27:19,229
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1038
ERROR_SCOPE Main Menu: save_results() takes from 3 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 1033, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 638, in sentence_identification
    save_results(feat, sub_sentences, sentence_info, sentence_file, database_file)
TypeError: save_results() takes from 3 to 4 positional arguments but 5 were given

ERROR_TIME: 2021-08-06 18:29:10,144
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1037
ERROR_SCOPE Main Menu: 'LanguageIndependentAnalysis' object is not iterable
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 1032, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 637, in sentence_identification
    save_results(feat, sentence_info, sentence_file, database_file)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 555, in save_results
    write_to_database(feat, sentence_info, database_file)
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 1059, in write_to_database
    for element in sentence:
TypeError: 'LanguageIndependentAnalysis' object is not iterable

ERROR_TIME: 2021-08-06 18:33:17,609
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1042
ERROR_SCOPE Main Menu: 'LanguageIndependentAnalysis' object is not iterable
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 1037, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 642, in sentence_identification
    save_results(feat, sentence_info, sentence_file, database_file)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 556, in save_results
    write_to_database(feat, sentence_info, database_file)
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 1059, in write_to_database
    for element in sentence:
TypeError: 'LanguageIndependentAnalysis' object is not iterable

ERROR_TIME: 2021-08-06 19:00:24,934
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1039
ERROR_SCOPE Main Menu: tuple index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 1034, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 636, in sentence_identification
    feature_info = sentence_info.feature_assignment()
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 425, in feature_assignment
    lit = self.calculate_scores()["LIT"]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 237, in calculate_scores
    dep_info = self.part_of_speech()[2]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 190, in part_of_speech
    morph = [word[5] for word in self.sub_sentences]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 190, in <listcomp>
    morph = [word[5] for word in self.sub_sentences]
IndexError: tuple index out of range

ERROR_TIME: 2021-08-06 19:01:50,445
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1039
ERROR_SCOPE Main Menu: tuple index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 1034, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 636, in sentence_identification
    feature_info = sentence_info.feature_assignment()
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 425, in feature_assignment
    lit = self.calculate_scores()["LIT"]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 237, in calculate_scores
    dep_info = self.part_of_speech()[2]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 190, in part_of_speech
    morph = [word[5] for word in self.sub_sentences]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 190, in <listcomp>
    morph = [word[5] for word in self.sub_sentences]
IndexError: tuple index out of range

ERROR_TIME: 2021-08-06 19:04:16,023
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1041
ERROR_SCOPE Main Menu: tuple index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 1036, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 638, in sentence_identification
    feature_info = sentence_info.feature_assignment()
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 425, in feature_assignment
    lit = self.calculate_scores()["LIT"]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 237, in calculate_scores
    dep_info = self.part_of_speech()[2]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 190, in part_of_speech
    morph = [word[5] for word in self.sub_sentences]
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_core_resources\app_auxiliary_functions.py", line 190, in <listcomp>
    morph = [word[5] for word in self.sub_sentences]
IndexError: tuple index out of range

ERROR_TIME: 2021-08-07 11:38:39,494
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1049
ERROR_SCOPE Main Menu: string indices must be integers
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 1044, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 659, in sentence_identification
    lit_score[element] = lit_score.get(element, 0) + classification[element]
TypeError: string indices must be integers

ERROR_TIME: 2021-08-07 12:44:30,675
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1031
ERROR_SCOPE No txt/xml selection: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 1028, in run_program
    doc = get_text(path_name)
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 257, in get_text
    with open(document, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: ''
