
ERROR_TIME: 2021-08-04 22:34:43,260
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 996
ERROR_SCOPE  'if __name__ == __main__': is due to '[Errno 2] No such file or directory: 'app_resources/app_common_default_docs/mueller_oral.txt')'
Traceback (most recent call last):
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/teki_main_app.py", line 979, in <module>
    run_program(default_doc, default_train,system_evaluation)
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/teki_main_app.py", line 867, in run_program
    doc = get_text(default_doc)
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/teki_main_app.py", line 170, in get_text
    with open(document, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/app_common_default_docs/mueller_oral.txt'

ERROR_TIME: 2021-08-04 22:39:57,025
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 939
ERROR_SCOPE Main Menu: [Errno 2] No such file or directory: 'app_resources/app_common_databases/oral_french.json'
Traceback (most recent call last):
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/teki_main_app.py", line 935, in run_program
    sentence_identification(collective_results_tagged, database, system_evaluation)
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/teki_main_app.py", line 548, in sentence_identification
    feat = sentence_info.feature_assignment()
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/app_resources/app_auxiliary_functions.py", line 372, in feature_assignment
    feat_1_score = sum(self.calculate_scores()["LIT"].values())
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/app_resources/app_auxiliary_functions.py", line 165, in calculate_scores
    oral_file = DiscourseAnalysis.read_database(feat_1)
  File "/Users/christopherchandler/PycharmProjects/bachleorarbeit/app_resources/app_auxiliary_functions.py", line 61, in read_database
    with open(infile, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources/app_common_databases/oral_french.json'
