
ERROR_TIME: 2021-08-11 12:27:56,271
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1074
ERROR_SCOPE Main Menu: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 1070, in run_program
    sentence_identification(collective_results_tagged,
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 711, in sentence_identification
    save_results(feat, sentence_info, corpus_sentence_id, sub_sentences, manual_file, database_file)
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 552, in save_results
    write_sentences(sentence, results_file=sentence_file, sen_num=sen_num,
  File "C:\Users\chris\Desktop\Teki\app_program_resources\app_auxiliary_functions.py", line 971, in write_sentences
    with open(results_file, mode="a", encoding="utf-8", newline="") as results:
FileNotFoundError: [Errno 2] No such file or directory: ''

ERROR_TIME: 2021-08-11 12:58:18,895
FILE_NAME: app_auxiliary_functions.py
MODULE: app_auxiliary_functions
                        
LINE_NO: 1050
ERROR_SCOPE Sub menu error: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Teki\app_program_resources\app_auxiliary_functions.py", line 1047, in sub_menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Teki\app_program_resources\app_auxiliary_functions.py", line 802, in evaluate_naive_bayes
    system = open(system_file, mode="r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: ''

ERROR_TIME: 2021-08-11 20:26:48,826
FILE_NAME: app_auxiliary_functions.py
MODULE: app_auxiliary_functions
                        
LINE_NO: 1038
ERROR_SCOPE invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Teki\app_program_resources\app_auxiliary_functions.py", line 1036, in sub_menu
    choice_num = int(choice_str)
ValueError: invalid literal for int() with base 10: ''

ERROR_TIME: 2021-08-11 21:22:59,732
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 1141
ERROR_SCOPE  'if __name__ == __main__': is due to 'EOF when reading a line)'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 1121, in <module>
    run_program(default_doc, default_train, system_evaluation)
  File "C:\Users\chris\Desktop\Teki\teki_main_app.py", line 1035, in run_program
    choice_str = input('\nPlease enter the number of your entry: ')
EOFError: EOF when reading a line
