 
ERROR_TIME: 2021-07-25 21:04:32,452
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                    
LINE_NO: 663
ERROR_NAME: Main Exception in division by zero)
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 649, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-25 21:05:28,563
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                    
LINE_NO: 665
ERROR_NAME: Main Exception in division by zero)
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 651, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-25 21:06:01,062
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                    
LINE_NO: 665
ERROR_LOCATION: Main Exception in division by zero)
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 651, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-25 21:06:23,578
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 665
ERROR_LOCATION: Main Exception in division by zero)
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 651, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-25 21:08:20,263
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 665
ERROR_DESCRIPTION Main Exception: is due to ' division by zero)'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 651, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-25 21:09:41,902
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 665
ERROR_LOCATION  'if __name__ == __main__': is due to ' division by zero)'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 651, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-25 21:10:18,824
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 665
ERROR_SCOPE  'if __name__ == __main__': is due to 'division by zero)'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 651, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-25 21:25:25,240
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 664
ERROR_SCOPE  'if __name__ == __main__': is due to '[Errno 2] No such file or directory: 'app_resources\\train_files\\cl_2_updated.csv')'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 655, in <module>
    run_program(default_doc, default_train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 604, in run_program
    freq = get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 400, in get_freq
    with open(file, mode="r", encoding="utf-8") as file_data:
FileNotFoundError: [Errno 2] No such file or directory: 'app_resources\\train_files\\cl_2_updated.csv'

ERROR_TIME: 2021-07-25 21:29:15,209
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 567
ERROR_SCOPE Main Exception in [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 563, in run_program
    doc = get_text(path_name)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 187, in get_text
    with open(document, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

ERROR_TIME: 2021-07-25 21:29:23,867
FILE_NAME: auxilary_functions.py
MODULE: auxilary_functions
                        
LINE_NO: 164
ERROR_SCOPE invalid literal for int() with base 10: '59+'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\auxilary_functions.py", line 162, in menu
    choice_num = int(choice_str)
ValueError: invalid literal for int() with base 10: '59+'

ERROR_TIME: 2021-07-25 21:41:40,609
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 592
ERROR_SCOPE string indices must be integers
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 587, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 365, in spacy_tagger
    sentence = corpus_content[key]
TypeError: string indices must be integers

ERROR_TIME: 2021-07-25 21:48:11,374
FILE_NAME: auxilary_functions.py
MODULE: auxilary_functions
                        
LINE_NO: 179
ERROR_SCOPE 'str' object has no attribute 'select'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\auxilary_functions.py", line 176, in menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 265, in extract_xml
    for tag in soup.select("div[id]"):
AttributeError: 'str' object has no attribute 'select'

ERROR_TIME: 2021-07-25 21:50:28,404
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 590
ERROR_SCOPE tuple indices must be integers or slices, not list
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 585, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 363, in spacy_tagger
    sentence = corpus_content[key]
TypeError: tuple indices must be integers or slices, not list

ERROR_TIME: 2021-07-25 21:51:14,522
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 661
ERROR_SCOPE  'if __name__ == __main__': is due to 'list index out of range)'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 652, in <module>
    run_program(default_doc, default_train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 601, in run_program
    freq = get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 407, in get_freq
    sentence_id = {(row[3], row[4], row[5]) for row in file_data}
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 407, in <setcomp>
    sentence_id = {(row[3], row[4], row[5]) for row in file_data}
IndexError: list index out of range

ERROR_TIME: 2021-07-25 21:51:37,347
FILE_NAME: auxilary_functions.py
MODULE: auxilary_functions
                        
LINE_NO: 179
ERROR_SCOPE 'str' object has no attribute 'select'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\auxilary_functions.py", line 176, in menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 265, in extract_xml
    for tag in soup.select("div[id]"):
AttributeError: 'str' object has no attribute 'select'

ERROR_TIME: 2021-07-25 21:51:43,516
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 590
ERROR_SCOPE 'function' object is not iterable
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 585, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 361, in spacy_tagger
    for key in corpus_content:
TypeError: 'function' object is not iterable

ERROR_TIME: 2021-07-25 21:52:43,813
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 590
ERROR_SCOPE tuple indices must be integers or slices, not list
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 585, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 363, in spacy_tagger
    sentence = corpus_content[key]
TypeError: tuple indices must be integers or slices, not list

ERROR_TIME: 2021-07-25 21:54:15,669
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 590
ERROR_SCOPE string indices must be integers
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 585, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 363, in spacy_tagger
    sentence = corpus_content[key]
TypeError: string indices must be integers

ERROR_TIME: 2021-07-25 21:57:34,272
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 591
ERROR_SCOPE tuple indices must be integers or slices, not list
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 586, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 364, in spacy_tagger
    sentence = corpus_content[key]
TypeError: tuple indices must be integers or slices, not list

ERROR_TIME: 2021-07-25 21:59:03,112
FILE_NAME: auxilary_functions.py
MODULE: auxilary_functions
                        
LINE_NO: 179
ERROR_SCOPE 'str' object has no attribute 'select'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\auxilary_functions.py", line 176, in menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 265, in extract_xml
    for tag in soup.select("div[id]"):
AttributeError: 'str' object has no attribute 'select'

ERROR_TIME: 2021-07-25 21:59:09,482
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 592
ERROR_SCOPE 'function' object is not iterable
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 587, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 363, in spacy_tagger
    for key in corpus_content:
TypeError: 'function' object is not iterable

ERROR_TIME: 2021-07-25 21:59:16,443
FILE_NAME: auxilary_functions.py
MODULE: auxilary_functions
                        
LINE_NO: 179
ERROR_SCOPE 'str' object has no attribute 'select'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\app_resources\auxilary_functions.py", line 176, in menu
    return options_func_dict()
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 265, in extract_xml
    for tag in soup.select("div[id]"):
AttributeError: 'str' object has no attribute 'select'

ERROR_TIME: 2021-07-25 21:59:17,393
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                        
LINE_NO: 592
ERROR_SCOPE 'function' object is not iterable
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 587, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 363, in spacy_tagger
    for key in corpus_content:
TypeError: 'function' object is not iterable
