
ERROR_TIME: 2021-07-25 15:47:03,738
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                    
LINE_NO: 658
ERROR_NAME: Main Exception in list index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 650, in <module>
    run_program(default_doc, default_train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 601, in run_program
    freq = get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 406, in get_freq
    sentence_id = {(row[3], row[4], row[5]) for row in file_data}
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 406, in <setcomp>
    sentence_id = {(row[3], row[4], row[5]) for row in file_data}
IndexError: list index out of range

ERROR_TIME: 2021-07-25 15:48:10,962
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                    
LINE_NO: 570
ERROR_NAME: Main Exception in [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 566, in run_program
    doc = get_text(path_name)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 187, in get_text
    with open(document, mode="r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

ERROR_TIME: 2021-07-25 15:49:34,330
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                    
LINE_NO: 658
ERROR_NAME: Main Exception in list index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 650, in <module>
    run_program(default_doc, default_train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 601, in run_program
    freq = get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 406, in get_freq
    sentence_id = {(row[3], row[4], row[5]) for row in file_data}
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 406, in <setcomp>
    sentence_id = {(row[3], row[4], row[5]) for row in file_data}
IndexError: list index out of range

ERROR_TIME: 2021-07-25 15:54:16,815
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
                    
LINE_NO: 660
ERROR_NAME: Main Exception in list index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 652, in <module>
    run_program(default_doc, default_train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 606, in run_program
    probs = get_probs(freq)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 435, in get_probs
    word, feat = element[0], element[5]
IndexError: list index out of range
