
ERROR_TIME: 2021-07-23 19:41:02,695
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 515
ERROR_NAME: list.extend() takes exactly one argument (2 given)
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 509, in run_program
    tagged = tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 293, in tagger
    result[i].extend(sentence_results,tag)
TypeError: list.extend() takes exactly one argument (2 given)

ERROR_TIME: 2021-07-23 19:44:35,930
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 515
ERROR_NAME: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 510, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 314, in identify_oral_literal
    sentence+=line[0]+" "
TypeError: can only concatenate tuple (not "str") to tuple

ERROR_TIME: 2021-07-23 19:49:07,245
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 515
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 510, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 336, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 19:53:35,345
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 516
ERROR_NAME: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 511, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 314, in identify_oral_literal
TypeError: can only concatenate tuple (not "str") to tuple

ERROR_TIME: 2021-07-23 20:01:24,010
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 522
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 517, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 342, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 20:02:01,470
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 522
ERROR_NAME: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 517, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 320, in identify_oral_literal
    sentence+=line[0]+" "
TypeError: can only concatenate tuple (not "str") to tuple

ERROR_TIME: 2021-07-23 20:02:42,089
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 522
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 517, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 342, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 20:04:49,159
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 524
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 519, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 344, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 20:05:12,185
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 524
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 519, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 344, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 20:05:25,155
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 524
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 519, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 344, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 20:08:33,598
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 529
ERROR_NAME: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 524, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 327, in identify_oral_literal
    sentence+=line[0]+" "
TypeError: can only concatenate tuple (not "str") to tuple

ERROR_TIME: 2021-07-23 20:13:48,910
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 529
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 524, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 349, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 20:14:26,289
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 529
ERROR_NAME: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 524, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 327, in identify_oral_literal
    sentence+=line[0]+" "
TypeError: can only concatenate tuple (not "str") to tuple

ERROR_TIME: 2021-07-23 20:15:20,263
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 529
ERROR_NAME: 'NOUN'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 524, in run_program
    identify_oral_literal(tagged)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 349, in identify_oral_literal
    if pos["NOUN"] > 2:
KeyError: 'NOUN'

ERROR_TIME: 2021-07-23 20:18:34,092
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 529
ERROR_NAME: local variable 'doc' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 519, in run_program
    content = analyze_content(doc,abbr)
UnboundLocalError: local variable 'doc' referenced before assignment

ERROR_TIME: 2021-07-23 20:45:35,062
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 542
ERROR_NAME: name 'tupl' is not defined
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 536, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 308, in spacy_tagger
    result[i].extend((sentence_results+tupl(tag)))
NameError: name 'tupl' is not defined

ERROR_TIME: 2021-07-23 20:45:54,567
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 542
ERROR_NAME: name 'tupl' is not defined
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 536, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 308, in spacy_tagger
    result[i].extend((sentence_results+tupl(tag)))
NameError: name 'tupl' is not defined

ERROR_TIME: 2021-07-23 20:48:13,077
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 542
ERROR_NAME: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 536, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 308, in spacy_tagger
    result[i].extend((sentence_results+tag))
TypeError: can only concatenate tuple (not "str") to tuple

ERROR_TIME: 2021-07-23 20:49:21,192
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 539
ERROR_NAME: can only concatenate tuple (not "list") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 533, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 304, in spacy_tagger
    result[i].extend((sentence_results+[tag]
TypeError: can only concatenate tuple (not "list") to tuple

ERROR_TIME: 2021-07-23 20:50:48,588
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 540
ERROR_NAME: can only concatenate tuple (not "list") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 534, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 306, in spacy_tagger
    result[i].extend((sentence_results+list(tag)))
TypeError: can only concatenate tuple (not "list") to tuple

ERROR_TIME: 2021-07-23 20:52:24,734
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 540
ERROR_NAME: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 534, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 306, in spacy_tagger
    result[i].extend((sentence_results+str(tag)))
TypeError: can only concatenate tuple (not "str") to tuple

ERROR_TIME: 2021-07-23 21:03:35,100
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 540
ERROR_NAME: bad operand type for unary +: 'tuple'
Traceback (most recent call last):
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 534, in run_program
    tagged = spacy_tagger(content)
  File "C:\Users\chris\iCloudDrive\Desktop\CodingProjects\Github\Bachleorarbeit\teki_main_app.py", line 305, in spacy_tagger
    result[i].extend((sentence_results,+tuple(tag)))
TypeError: bad operand type for unary +: 'tuple'

ERROR_TIME: 2021-07-23 22:59:08,581
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 530
ERROR_NAME: [E050] Can't find model 'fr_core_news_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
Traceback (most recent call last):
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 524, in run_program
    tagged = spacy_tagger(content)
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 300, in spacy_tagger
    nlp = spacy.load("fr_core_news_sm")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/spacy/util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'fr_core_news_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
Traceback (most recent call last):
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/app_resources/auxilary_functions.py", line 104, in menu
    return options_func_dict()
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 235, in extract_xml
    corpus_tag_choice = input("Please enter a valid tag: ")
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/app_resources/auxilary_functions.py", line 104, in menu
    return options_func_dict()
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 235, in extract_xml
    corpus_tag_choice = input("Please enter a valid tag: ")
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/app_resources/auxilary_functions.py", line 104, in menu
    return options_func_dict()
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 235, in extract_xml
    corpus_tag_choice = input("Please enter a valid tag: ")
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/app_resources/auxilary_functions.py", line 104, in menu
    return options_func_dict()
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 235, in extract_xml
    corpus_tag_choice = input("Please enter a valid tag: ")
KeyboardInterrupt

ERROR_TIME: 2021-07-24 00:49:14,885
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 256
ERROR_NAME: local variable 'corpus_text' referenced before assignment
Traceback (most recent call last):
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 242, in extract_xml
    results = sentence_tokenizer(corpus_text, abbr)
UnboundLocalError: local variable 'corpus_text' referenced before assignment
Traceback (most recent call last):
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/app_resources/auxilary_functions.py", line 104, in menu
    return options_func_dict()
  File "/Users/christopherchandler/Documents/Academic Documents/RUB UNI/0 - Files/Lingustik PL/B.A/B.A./Bachleorarbeit/teki_main_app.py", line 235, in extract_xml
    corpus_tag_choice = input("Please enter a valid tag: ")
KeyboardInterrupt

ERROR_TIME: 2021-07-24 08:05:24,006
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 574
ERROR_NAME: string index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 568, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 528, in run_program
    freq=get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 343, in get_freq
    if row[4]==feat_1:
IndexError: string index out of range

ERROR_TIME: 2021-07-24 08:06:16,015
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 574
ERROR_NAME: local variable 'train' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 568, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 528, in run_program
    freq=get_freq(train)
UnboundLocalError: local variable 'train' referenced before assignment

ERROR_TIME: 2021-07-24 08:08:00,094
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 516
ERROR_NAME: local variable 'doc' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 506, in run_program
    content = analyze_content(doc,abbr)
UnboundLocalError: local variable 'doc' referenced before assignment

ERROR_TIME: 2021-07-24 08:08:08,786
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 573
ERROR_NAME: string index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 567, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 527, in run_program
    freq=get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 343, in get_freq
    if row[4]==feat_1:
IndexError: string index out of range

ERROR_TIME: 2021-07-24 08:08:55,548
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 574
ERROR_NAME: string index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 568, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 528, in run_program
    freq=get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 344, in get_freq
    if row[4]==feat_1:
IndexError: string index out of range

ERROR_TIME: 2021-07-24 08:11:02,630
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 580
ERROR_NAME: name 'database' is not defined
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 574, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 534, in run_program
    freq=get_freq(train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 338, in get_freq
    with open(database, mode="r", encoding="utf-8") as data:
NameError: name 'database' is not defined

ERROR_TIME: 2021-07-24 08:11:42,999
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 580
ERROR_NAME: string index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 574, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 537, in run_program
    probs = get_probs(freq, train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 368, in get_probs
    feat=word[4]
IndexError: string index out of range

ERROR_TIME: 2021-07-24 08:14:15,837
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 578
ERROR_NAME: local variable 'train' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 572, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 532, in run_program
    freq=get_freq(train)
UnboundLocalError: local variable 'train' referenced before assignment

ERROR_TIME: 2021-07-24 08:14:32,847
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 578
ERROR_NAME: string index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 572, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 535, in run_program
    probs = get_probs(freq, train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 366, in get_probs
    feat=word[4]
IndexError: string index out of range

ERROR_TIME: 2021-07-24 08:16:14,809
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 583
ERROR_NAME: string index out of range
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 577, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 540, in run_program
    probs = get_probs(freq, train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 371, in get_probs
    feat=word[4]
IndexError: string index out of range

ERROR_TIME: 2021-07-24 08:22:42,058
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 589
ERROR_NAME: name 'csv_data' is not defined
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 583, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 546, in run_program
    probs = get_probs(freq)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 384, in get_probs
    for word in csv_data:
NameError: name 'csv_data' is not defined

ERROR_TIME: 2021-07-24 08:23:24,439
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 589
ERROR_NAME: tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 583, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 549, in run_program
    classify(text, probs, freq)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 408, in classify
    true = prior_prob["ORAL"] / (prior_prob["ORAL"] + prior_prob["LIT"])
TypeError: tuple indices must be integers or slices, not str

ERROR_TIME: 2021-07-24 08:28:34,326
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 592
ERROR_NAME: tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 586, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 552, in run_program
    classify(text, probs, freq)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 411, in classify
    true = prior_prob["ORAL"] / (prior_prob["ORAL"] + prior_prob["LIT"])
TypeError: tuple indices must be integers or slices, not str

ERROR_TIME: 2021-07-24 10:05:28,329
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 557
ERROR_NAME: classify() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 551, in <module>
    run_program(debug)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 517, in run_program
    classify(text, probs, freq)
TypeError: classify() takes 2 positional arguments but 3 were given

ERROR_TIME: 2021-07-24 10:33:30,564
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 505
ERROR_NAME: identify_oral_literal() missing 1 required positional argument: 'database'
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 500, in run_program
    identify_oral_literal(tagged)
TypeError: identify_oral_literal() missing 1 required positional argument: 'database'

ERROR_TIME: 2021-07-24 10:35:12,029
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 505
ERROR_NAME: local variable 'train' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 500, in run_program
    identify_oral_literal(tagged,train)
UnboundLocalError: local variable 'train' referenced before assignment

ERROR_TIME: 2021-07-24 10:35:26,479
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 505
ERROR_NAME: local variable 'doc' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 495, in run_program
    content = analyze_content(doc,abbr)
UnboundLocalError: local variable 'doc' referenced before assignment

ERROR_TIME: 2021-07-24 10:37:24,808
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 563
ERROR_NAME: Main Exceptiondivision by zero
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 553, in <module>
    4/0
ZeroDivisionError: division by zero

ERROR_TIME: 2021-07-24 10:42:57,117
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 506
ERROR_NAME: local variable 'train' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 501, in run_program
    identify_oral_literal(tagged,train)
UnboundLocalError: local variable 'train' referenced before assignment

ERROR_TIME: 2021-07-24 10:43:44,962
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 506
ERROR_NAME: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 501, in run_program
    identify_oral_literal(tagged,train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 335, in identify_oral_literal
    i+=1
TypeError: can only concatenate tuple (not "int") to tuple

ERROR_TIME: 2021-07-24 10:44:49,721
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 506
ERROR_NAME: 'int' object is not iterable
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 501, in run_program
    identify_oral_literal(tagged,train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 334, in identify_oral_literal
    res(sentence_info[entry], "LIT", id+tuple(l))
TypeError: 'int' object is not iterable

ERROR_TIME: 2021-07-24 10:45:49,959
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 506
ERROR_NAME: 'int' object is not iterable
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 501, in run_program
    identify_oral_literal(tagged,train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 334, in identify_oral_literal
    res(sentence_info[entry], "LIT", id+tuple(l))
TypeError: 'int' object is not iterable

ERROR_TIME: 2021-07-24 10:48:48,050
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 247
ERROR_NAME: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 229, in extract_xml
    choice = int(corpus_tag_choice)
ValueError: invalid literal for int() with base 10: ''

ERROR_TIME: 2021-07-24 10:49:12,852
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 506
ERROR_NAME: can only concatenate str (not "tuple") to str
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 501, in run_program
    identify_oral_literal(tagged,train)
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 334, in identify_oral_literal
    res(sentence_info[entry], "LIT", id+tuple(str(l)))
TypeError: can only concatenate str (not "tuple") to str

ERROR_TIME: 2021-07-24 17:17:56,025
FILE_NAME: teki_main_app.py
MODULE: teki_main_app
LINE_NO: 506
ERROR_NAME: local variable 'doc' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\chris\Desktop\Bachleorarbeit\teki_main_app.py", line 496, in run_program
    content = analyze_content(doc,abbr)
UnboundLocalError: local variable 'doc' referenced before assignment
